import React, { useState } from 'react';
import { GoogleGenAI } from "@google/genai";
import { Terminal, Sparkles, RefreshCw, Zap, AlertCircle, CheckCircle2 } from 'lucide-react';
import { Reveal } from './Reveal';

const PracticePlayground: React.FC = () => {
  const [input, setInput] = useState('');
  const [response, setResponse] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [shake, setShake] = useState(false);

  const validateInput = (text: string) => {
    // Basic heuristic: Must have reasonable length and contain spaces (words)
    const trimmed = text.trim();
    if (trimmed.length < 15) return "Prompt is too short. Please add more detail.";
    if (!trimmed.includes(' ')) return "Please enter a valid sentence, not just random characters.";
    // Check for gibberish (simple check for repeated chars or lack of vowels could go here, but length+space is a good start)
    const distinctChars = new Set(trimmed).size;
    if (distinctChars < 5) return "This doesn't look like a valid prompt.";
    
    return null;
  };

  const handleSimulate = async () => {
    setError(null);
    setResponse(null);

    const validationError = validateInput(input);
    if (validationError) {
      setError(validationError);
      setShake(true);
      setTimeout(() => setShake(false), 500); // Reset shake
      return;
    }

    setLoading(true);
    
    try {
      const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
      const result = await ai.models.generateContent({
        model: 'gemini-2.5-flash',
        contents: input,
        config: {
          systemInstruction: "You are a helpful AI assistant simulating a response for a prompt engineering practice tool. Your goal is to show the user what a good response to their prompt looks like. Keep your answer concise (under 150 words) but high quality. If the user's prompt is weak, give a generic but helpful answer. If strong, give a specific and detailed answer."
        }
      });
      setResponse(result.text);
    } catch (e) {
      console.error(e);
      setError("Failed to generate response. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <section className="py-24 bg-slate-950 relative overflow-hidden border-t border-slate-900">
      {/* Background Decor */}
      <div className="absolute top-0 right-0 w-1/2 h-full bg-slate-900 skew-x-12 transform translate-x-32 border-l border-white/5"></div>
      <div className="absolute bottom-0 left-0 w-[500px] h-[500px] bg-blue-900/20 rounded-full blur-[120px]"></div>
      
      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        <Reveal>
          <div className="text-center mb-16">
             <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-blue-900/30 border border-blue-500/30 text-blue-400 text-xs font-bold uppercase tracking-widest mb-6 shadow-sm">
                <Terminal className="w-4 h-4" />
                Interactive Sandbox
             </div>
             <h2 className="text-4xl lg:text-5xl font-extrabold text-white mb-6">Practice Your <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-purple-400">Prompt</span></h2>
             <p className="text-slate-400 text-lg max-w-2xl mx-auto">
                Don't just read about it. Type a prompt below to see how it feels. 
                <br />Get a real response generated by Gemini AI.
             </p>
          </div>
        </Reveal>

        <div className="bg-slate-900/50 backdrop-blur-xl rounded-[2.5rem] shadow-2xl shadow-blue-500/10 border border-white/10 overflow-hidden flex flex-col md:flex-row min-h-[550px] ring-1 ring-white/5 group">
            
            {/* Input Side */}
            <div className="flex-1 p-8 md:p-10 flex flex-col border-b md:border-b-0 md:border-r border-white/10 bg-slate-900/80 relative">
                <div className="flex items-center justify-between mb-6">
                    <label className="text-xs font-bold text-slate-400 uppercase tracking-widest flex items-center gap-2">
                        <div className="w-2 h-2 rounded-full bg-blue-500 animate-pulse"></div>
                        Prompt Input
                    </label>
                </div>
                
                <div className={`relative flex-grow flex flex-col transition-all duration-300 ${shake ? 'animate-shake' : ''}`}>
                   <textarea 
                      className={`flex-grow w-full bg-slate-950/50 rounded-2xl p-6 text-slate-200 font-medium text-lg focus:outline-none focus:ring-2 focus:bg-slate-950 border resize-none transition-all placeholder:text-slate-600 leading-relaxed font-mono
                        ${error ? 'border-red-500/50 focus:ring-red-500/20 focus:border-red-500' : 'border-white/5 focus:ring-blue-500/20 focus:border-blue-500/50'}
                      `}
                      placeholder="Type your prompt here... e.g. 'Act as a historian...'"
                      value={input}
                      onChange={(e) => {
                        setInput(e.target.value);
                        if(error) setError(null);
                      }}
                  ></textarea>
                  
                  {error && (
                    <div className="absolute bottom-4 left-4 right-4 flex items-center gap-2 text-red-400 bg-slate-900/95 backdrop-blur-sm p-3 rounded-xl border border-red-500/30 shadow-lg animate-float">
                      <AlertCircle className="w-4 h-4 flex-shrink-0" />
                      <span className="text-xs font-bold">{error}</span>
                    </div>
                  )}
                </div>
                
                <div className="mt-8 flex justify-between items-center">
                    <span className={`text-xs font-medium transition-colors ${input.length > 0 ? 'text-blue-400' : 'text-slate-600'}`}>
                        {input.length} characters
                    </span>
                    <button 
                        onClick={handleSimulate}
                        disabled={loading || !input.trim()}
                        className="px-8 py-3.5 bg-blue-600 text-white rounded-xl font-bold hover:bg-blue-500 disabled:opacity-50 disabled:cursor-not-allowed disabled:bg-slate-800 transition-all flex items-center gap-3 shadow-lg shadow-blue-600/20 hover:shadow-blue-600/40 hover:-translate-y-1 active:translate-y-0"
                    >
                        {loading ? <RefreshCw className="w-5 h-5 animate-spin" /> : <Zap className="w-5 h-5 fill-current" />}
                        {loading ? 'Processing...' : 'Run Prompt'}
                    </button>
                </div>
            </div>

            {/* Output Side */}
            <div className="flex-1 bg-black/20 p-8 md:p-10 flex flex-col relative overflow-hidden">
                {/* Decorative Grid */}
                <div className="absolute inset-0 bg-grid-slate-200/[0.05] opacity-50 pointer-events-none"></div>

                <div className="flex items-center justify-between mb-6 relative z-10">
                    <label className="text-xs font-bold text-slate-500 uppercase tracking-widest flex items-center gap-2">
                        <Sparkles className="w-4 h-4 text-purple-400" />
                        AI Output
                    </label>
                </div>
                
                <div className="flex-grow rounded-2xl border border-white/5 bg-slate-950/50 backdrop-blur-sm p-8 relative shadow-inner z-10 overflow-y-auto custom-scrollbar">
                    {!response && !loading && (
                        <div className="absolute inset-0 flex flex-col items-center justify-center text-slate-600">
                            <Terminal className="w-12 h-12 mb-4 opacity-20" />
                            <p className="text-center font-medium">Results will appear here</p>
                        </div>
                    )}

                    {loading && (
                        <div className="space-y-6 animate-pulse p-4">
                            <div className="flex gap-4">
                                <div className="w-8 h-8 bg-blue-500/20 rounded-full"></div>
                                <div className="flex-1 space-y-3">
                                    <div className="h-4 bg-slate-800 rounded w-3/4"></div>
                                    <div className="h-4 bg-slate-800 rounded w-full"></div>
                                    <div className="h-4 bg-slate-800 rounded w-5/6"></div>
                                </div>
                            </div>
                        </div>
                    )}

                    {response && (
                        <div className="prose prose-invert max-w-none">
                            <div className="flex items-start gap-4">
                                <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-blue-500 to-purple-600 flex items-center justify-center flex-shrink-0 mt-1 shadow-lg shadow-blue-500/30 text-white">
                                    <Sparkles className="w-4 h-4" />
                                </div>
                                <div>
                                    <p className="text-slate-300 whitespace-pre-line leading-relaxed font-medium text-lg font-sans">
                                        {response}
                                    </p>
                                    <div className="mt-6 flex items-center gap-2 text-emerald-400 text-xs font-bold uppercase tracking-wider bg-emerald-500/10 px-3 py-1.5 rounded-full w-fit border border-emerald-500/20">
                                      <CheckCircle2 className="w-3 h-3" /> Generation Complete
                                    </div>
                                </div>
                            </div>
                        </div>
                    )}
                </div>
                
                <div className="mt-6 flex justify-center relative z-10">
                    <p className="text-[10px] text-slate-600 font-medium uppercase tracking-widest flex items-center gap-1">
                        Powered by <span className="text-blue-500 font-bold">Google Gemini</span>
                    </p>
                </div>
            </div>
        </div>
      </div>
    </section>
  );
};

export default PracticePlayground;